groups:
  - name: example
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 2m  # Change this to 2 minutes
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
