version: '2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /opt/monitoring/prom:/etc/prometheus
      - /prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=20d'
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    user: "472:472"
    ports:
      - "3000:3000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - /grafana-backup/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=.............
    restart: unless-stopped


  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes:
  grafana_data:
